### ISSUE TITLE
ledPosition always leads to LED on the left

### ISSUE THREAD

**Issue by kcgthb** [hundio/status.js#1]
Hi, 

I'm trying to move the led to the right of state text by using the `ledPosition` display option, but can't seem to make it work. 

The doc refers to `either "left" or "right"`:

```
  display: {
    hideOnError: true, // Hide the widget if a connection cannot be established
    ledOnly: false, // Show only the LED indicator, hiding the status text
    panePosition: "bottom-right", // One of "top-left", "top-right", "bottom-left", "bottom-right"
    ledPosition: "left", // Either "left" or "right"
  },
```
but whatever value `ledPosition` is set to, the LED always shows up on the left of the text.

Could you please confirm that setting it to "right" should move the LED to the right?

**Comment by laCour** [comment]
Thanks for reporting this! [Version 2.1.1](https://github.com/hundio/status.js/releases/tag/v2.1.1) corrects this, so `"right"` will now properly align the LED as expected.

**Comment by kcgthb** [comment]
I can confirm that version 2.1.1 fixes the issue.
Thanks for the lightning-fast fix!
