### ISSUE TITLE
Widget doesn't report outages

### ISSUE THREAD

**Issue by kcgthb** [hundio/status.js#2]
Hi!

I just noticed that the widget does not seem to report automatically-generated outages, ie. the ones that are reported by external metric sources:

![status](https://user-images.githubusercontent.com/186807/27262534-2b420214-540d-11e7-8046-d06583d82813.png)

The LED status correctly turns red, but the detailed status message says "No issue". Does it only report manually created issues?

Thanks!

**Comment by laCour** [comment]
Thanks for reporting this!

At the moment, our [live event streams](https://hund.io/help/documentation/live-event-streams) do not provide granular statuses on the `init_event`, so it's not possible to indicate which components are non-operational on the widget. This may change in the future.

The widget's pane could clarify that component(s) are degraded. The pane currently only lists issues. Only stating that there are "currently no issues" is confusing in this case. I'll work on integrating the current state into the pane's wording.

Let me know if you have any suggestions!

**Comment by kcgthb** [comment]
That'd be great, thanks for the clarification!
