### ISSUE TITLE
statistics report NaN

### ISSUE THREAD

**Issue by kcgthb** [hundio/status.js#6]
Hi!

I just tried the new 3.5.0 version, and noticed that the widget correctly added a "statistics" section, but seem to fail reporting actual values. It currenlty reports:
> NaN% UptimeNo events for almost NaN years!

Anything I need to change in my config?

**Comment by kcgthb** [comment]
Gotcha, thanks for the clarification!

**Comment by laCour** [comment]
The update has completed, and statistics are now available. Have a great weekend!

**Comment by kcgthb** [comment]
Excellent, works great now, thank you!
